#cloud-config
packages:
  - curl
users:
  - name: cluster
    ssh-authorized-keys:
      - ${ssh_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
runcmd:
  - apt-get update -y
  - curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik server --advertise-address=${k3s_advertise_address} --write-kubeconfig-mode=644" sh -
  - chown cluster:cluster /etc/rancher/k3s/k3s.yaml
  - ip addr add ${k3s_advertise_address}/32 dev eth0
  - sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
  - chmod o+r /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  - chmod o+r /etc/apt/sources.list.d/caddy-stable.list
  - sudo apt update
  - sudo apt install caddy

