#cloud-config
packages:
  - curl
users:
  - name: cluster
    ssh-authorized-keys:
      - ${ssh_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
runcmd:
  - apt-get update -y
  - curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik server --write-kubeconfig-mode=644" sh -
  - chown cluster:cluster /etc/rancher/k3s/k3s.yaml
  - cat /etc/rancher/k3s/k3s.yaml